elastic_password: ENC[AES256_GCM,data:GbaMnT7rMaNfK8h2zWx2GmIILkZ7xdQZ39h9JKHZGUo=,iv:DlrTAsDXqvXmnbS76X1to5Jodjw2l1M8j4mV6DYxBwo=,tag:5jLQiLwk+IZPeQFHyTyalA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdmNZWThsOGpqQWxBMklP
            MXNrZitjbGRGRmpFRjNKeHg1WVFiMkszZmlzCkRsQk5oTXUra25DVzZLMTBPbjZJ
            eVRuYWFuK1Y4dlRJL2h2NWE1dVl3dkkKLS0tIHkzL1hUc2hHTjdTQjVDaUZEemlx
            MDNRaVBCWk4zUWtFaVZ6cE96OTVQNEkK8KOChXRTYEOocYUPtCdAfkG3c9ep0pCf
            uYrE/2PmLWeNfnuSonMcT8xJR/+HV6FRPMWt1h2ZJSoH7A1UfwbUSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fucsvstpr082zemctfpjn2xkwq86thvlzan4tp9fyvg2q0rnnemshw690m
    lastmodified: "2026-10-07T22:37:17Z"
    mac: ENC[AES256_GCM,data:bXlGmFYP0nXB5o15zVPCbCJY/ZamGllVqshPOFvsLlxRex8vywCJMSFezG75zNoISPMvuULyyG8DWC1t/eLNag+RKeiURMwpHFhBpelmuK0JP35f+3fdl4mWOpPdmdxJrbt6mzmvT77npKAvdXzsLOlrLFozgAr9Mo+6m0qRizg=,iv:m1vm9iXmBY1+ylJTpRQSlnqUuqj1qAX6hl17fjMGDM0=,tag:0vM/fax9DSrHZ4mqej58MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
