galaxy_info:
  author: Bruno Cochofel
  description: Logstash from Elastic's DEB package, Elastic Agent input over mTLS
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
