# Code generated into every stack tagged "config" and "elastic": the
# Elastic stack's own configuration (ILM, Fleet, Kibana), applied after
# Ansible has installed it. Edit here, then `terramate generate`; never
# edit the _terramate_generated_*.tf files by hand.
#
# Credentials: one Elasticsearch API key, ELASTICSEARCH_API_KEY in
# ~/.secrets/homelab.yaml (`mise run tofu:*`, docs/CREDENTIALS.md). The
# provider reads it from the environment; Kibana and Fleet reuse it.

generate_hcl "_terramate_generated_backend.tf" {
  condition = tm_contains(terramate.stack.tags, "config") && tm_contains(terramate.stack.tags, "elastic")

  content {
    terraform {
      required_version = "> 1.9.0, < 2.0"

      # elasticstack, plus any provider a stack adds through the
      # elastic_extra_providers global (one required_providers per module).
      tm_dynamic "required_providers" {
        attributes = tm_merge({
          elasticstack = {
            source  = "elastic/elasticstack"
            version = "~> 0.16.5"
          }
        }, global.elastic_extra_providers)
      }

      # HCP Terraform, state only (execution mode Local), as for the infra
      # stacks.
      cloud {
        hostname     = "app.terraform.io"
        organization = global.hcp_organization

        workspaces {
          name = global.hcp_workspace
        }
      }
    }
  }
}

generate_hcl "_terramate_generated_elasticstack.tf" {
  condition = tm_contains(terramate.stack.tags, "config") && tm_contains(terramate.stack.tags, "elastic")

  content {
    provider "elasticstack" {
      elasticsearch {
        endpoints = global.elastic.es_endpoints
        ca_file   = "${path.module}/${terramate.stack.path.to_root}/${global.elastic.ca_cert}"
      }

      kibana {
        endpoints = [global.elastic.kibana_endpoint]
        ca_certs  = ["${path.module}/${terramate.stack.path.to_root}/${global.elastic.ca_cert}"]
      }

      fleet {
        endpoint = global.elastic.kibana_endpoint
        ca_certs = ["${path.module}/${terramate.stack.path.to_root}/${global.elastic.ca_cert}"]
      }
    }
  }
}

# No variables (the API key comes from the environment), but TFLint's
# terraform_standard_module_structure wants the file.
generate_file "variables.tf" {
  condition = tm_contains(terramate.stack.tags, "config") && tm_contains(terramate.stack.tags, "elastic")
  content   = "# Generated by Terramate (stacks/config.tm.hcl). No variables: the\n# Elasticsearch API key comes from ELASTICSEARCH_API_KEY.\n"
}
